shared__test_vm__hostname: "localhost"

shared__test_vm__username: "roman"

test_vm__ssh_port: "22"
shared__test_vm__ssh_host: "test_vm_01"
shared__test_vm__ssh_dropbear_root_host: "{{ shared__test_vm__ssh_host }}_root"


test_vm__bitwarden__item_name: "server_home"

ansible_tmp_dir_path: "/tmp/ansible"

debian_version: "12.5.0"
debian_architecture: "amd64" # "arm64"
debian_preseed_iso_name: "debian_{{ debian_version }}_{{ debian_architecture }}_preseed.iso"

debian_vm_tmp_dir_path: "{{ ansible_tmp_dir_path }}/debian_vm"
debian_vm_tmp_scripts_dir_path: "{{ debian_vm_tmp_dir_path }}/scripts"
debian_vm_tmp_iso_dir_path: "{{ debian_vm_tmp_dir_path }}/iso"
debian_vm_tmp_files_dir_path: "{{ debian_vm_tmp_dir_path }}/files"
debian_vm_tmp_iso_file_path: "{{ debian_vm_tmp_iso_dir_path }}/{{ debian_preseed_iso_name }}"

debian_vm_image_name: "debian"
debian_vm_image_format: "qcow2"
debian_vm_image_file: "{{ debian_vm_image_name }}.{{ debian_vm_image_format }}"
debian_vm_tmp_image_file_path: "{{ debian_vm_tmp_files_dir_path }}/{{ debian_vm_image_file }}"

debian_vm_hdd_image_quantity: 3
debian_vm_hdd_image_name: "debian_hdd"
debian_vm_hdd_image_format: "qcow2"
debian_vm_hdd_image_file: "{{ debian_vm_hdd_image_name }}.{{ debian_vm_hdd_image_format }}"
debian_vm_hdd_image_file_path: "{{ debian_vm_tmp_files_dir_path }}/{{ debian_hdd_image_file }}"

debian_vm_initrd_img_name: "initrd.img-6.1.0-18-{{ debian_architecture }}"
debian_vm_kernel_img_name: "vmlinuz-6.1.0-18-{{ debian_architecture }}"
debian_vm_persistent_dir_path: "~/debian_preseed_vm"

debian_vm_ip: "10.0.2.254"
debian_vm_dhcp_start_address: "10.0.2.254"
debian_vm_dhcp_end_address: "10.0.2.3"
debian_vm_dhcp_subnet_mask: "255.255.255.0"
debian_vm_net: "10.0.2.0/24"


debian_vm_initrd_img_file_path: "{{ debian_vm_tmp_files_dir_path }}/{{ debian_vm_initrd_img_name }}"
debian_vm_kernel_img_file_path: "{{ debian_vm_tmp_files_dir_path }}/{{ debian_vm_kernel_img_name }}"

qemu_monitor_socket_path: "/tmp/qemu_monitor.socket"

debian_vm__ssh_dropbear_root_password: "" # set in playbook
debian_vm__crypt_password: "" # set in playbook