---
- name: Create login item
  bitwarden_create:
    type: "item"
    name: "{{ item.name }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    folder_name: "{{ item.folder_name }}"
    folder_id: "{{ item.folder_id }}"
  register: bitwarden__create_item__login_result
  loop: "{{ bitwarden__create_item__data_dict_list }}"
  when: item.type == 'login'

