---
- name: Run when at least one disk found
  when:
    - fstab__add_entry__data_list | length > 0
  become: true
  block:
    - name: Create mount folders for {{ fstab__add_entry__data_list }}
      ansible.builtin.file:
        path: "{{ mount_dir_path }}"
        state: directory
        owner: "{{ item.mount_dir_owner }}"
        group: "{{ item.mount_dir_owner }}"
        mode: '0755'
      loop: "{{ fstab__add_entry__data_list }}"
      vars:
        mount_dir_path: 
          "{{ item.mount_root_dir_path }}/{{ item.partition_name }}"

    - name: Add fstab entry for {{ fstab__add_entry__data_list }}
      ansible.builtin.lineinfile:
        path: "/etc/fstab"
        insertafter: EOF
        line: "{{ fstab_line }}"
        regexp: "{{ fstab_line }}"
        create: true
      loop: "{{ fstab__add_entry__data_list }}"
      vars:
        mount_dir_path: 
          "{{ item.mount_root_dir_path }}/{{ item.partition_name }}"
        fstab_line: >-
          {{ item.partition_path }}
          {{ mount_dir_path }}
          {{ item.partition_filesystem }}
          noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=
          {{- item.systemd_idle_timeout_sec }} 0 0

    - name: Set fact 'fstab__add_entry__load_automount'
      ansible.builtin.set_fact:
        fstab__add_entry__load_automount: >-
          {{ fstab__add_entry__load_automount | default([]) + [append] }}
      loop: "{{ fstab__add_entry__data_list }}"
      vars:
        append:
          "{{ item.mount_root_dir_name }}-{{ item.partition_name }}.automount"
      changed_when: true

    - ansible.builtin.debug: msg="trigger load automount"
      notify: "load automount"
      changed_when: true

