bitwarden_get_field__data_dict_list:
  - bitwarden__get_field__fact_name: "bitwarden__get_password__result"
    bitwarden__get_field__entry_name: "{{ bitwarden_item_name }}"
    bitwarden__get_field__field_name: "password"

############################################################################################################

vm__start_debian__become: true
vm__start_debian__is_encrypted: "{{ debian_vm_encrypt_boot_drive }}"
vm__start_debian__ssh_port: "{{ ssh_port }}"
vm__start_debian__ssh_host: "{{ hostname }}"
vm__start_debian__ssh_dropbear_root_host: "{{ ssh_dropbear_root_host }}"
vm__start_debian__ssh_dropbear_root_password: "{{ bitwarden__get_password__result }}"
vm__start_debian__crypt_password: "{{ bitwarden__get_password__result }}"
vm__start_debian__vm_tmp_files_dir_path: "{{ tmp_files_dir_path }}"
vm__start_debian__vm_tmp_dir_path: "{{ tmp_dir_path }}"
vm__start_debian__vm_tmp_scripts_dir_path: "{{ tmp_scripts_dir_path }}"
vm__start_debian__vm_persistent_dir_path: "{{ debian_vm_persistent_dir_path }}"
vm__start_debian__hdd_image_name: "{{ debian_vm_hdd_image_name  }}"
vm__start_debian__hdd_image_format: "{{ debian_vm_hdd_image_format }}"
vm__start_debian__hdd_image_quantity: "{{ debian_vm_hdd_image_quantity }}"
vm__start_debian__vm__hostname: "{{ hostname }}"
vm__start_debian__vm_kernel_img_file_path: "{{ debian_vm_kernel_img_file_path }}"
vm__start_debian__vm_initrd_img_file_path: "{{ debian_vm_initrd_img_file_path }}"
vm__start_debian__vm_net: "{{ debian_vm_net }}"
vm__start_debian__vm_dhcp_start_address: "{{ debian_vm_dhcp_start_address }}"
vm__start_debian__vm_tmp_image_file_path: "{{ debian_vm_tmp_image_file_path }}"
vm__start_debian__vm_image_format: "{{ debian_vm_image_format }}"
vm__start_debian__vm_files_dir_path: "{{ tmp_files_dir_path }}"