---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance-1
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../group_vars
verifier:
  name: ansible

