iso__create_debian_preseed__sudo_without_password: true
iso__create_debian_preseed__preseed_ip: "{{ debian_vm_ip }}"
iso__create_debian_preseed__preseed_gateway_ip: "{{ debian_vm_dhcp_start_address }}"
iso__create_debian_preseed__preseed_subnet_mask: "{{ debian_vm_dhcp_subnet_mask }}"

############################################################################################################

vm__setup_debian__scripts_dir_path: "{{ tmp_scripts_dir_path }}"
vm__setup_debian__files_dir_path: "{{ tmp_files_dir_path }}"
vm__setup_debian__iso_dir_path: "{{ tmp_iso_dir_path }}"
vm__setup_debian__image_file: "{{ debian_vm_image_file }}"
vm__setup_debian__image_size: 20G
vm__setup_debian__ssh_port: "{{ ssh__create_config__port }}"
vm__setup_debian__ssh_host: "{{ debian_vm_ip }}"
vm__setup_debian__is_encrypted: "{{ iso__create_debian_preseed__encrypt_boot_drive }}"
vm__setup_debian__crypt_password: "{{ debian_vm__crypt_password }}"
vm__setup_debian__ssh_dropbear_root_host: "{{ ssh_dropbear_root_host }}"
vm__setup_debian__ssh_dropbear_root_password: "{{ debian_vm__ssh_dropbear_root_password }}"
vm__setup_debian__hdd_image_name: "{{ debian_vm_hdd_image_name  }}"
vm__setup_debian__hdd_image_format: "{{ debian_vm_hdd_image_format }}"
vm__setup_debian__hdd_image_quantity: "{{ debian_vm_hdd_image_quantity }}"
vm__setup_debian__qemu_monitor_socket_path: "{{ qemu_monitor_socket_path }}"
vm__setup_debian__vm_net: "{{ debian_vm_net }}"
vm__setup_debian__vm_dhcp_start_address: "{{ debian_vm_dhcp_start_address }}"
vm__setup_debian__vm_tmp_image_file_path: "{{ debian_vm_tmp_image_file_path }}"
vm__setup_debian__vm_image_format: "{{ debian_vm_image_format }}"
vm__setup_debian__vm_tmp_iso_file_path: "{{ tmp_iso_file_path }}"
vm__setup_debian__vm_ip: "{{ debian_vm_ip }}"
vm__setup_debian__vm_tmp_dir_path: "{{ tmp_dir_path }}"
vm__setup_debian__vm_persistent_dir_path: "{{ debian_vm_persistent_dir_path }}"
vm__setup_debian__vm_kernel_img_name: "{{ debian_vm_kernel_img_name }}"
vm__setup_debian__vm_initrd_img_name: "{{ debian_vm_initrd_img_name }}"
