---
- name: register latest docker-compose version
  shell: set -o pipefail && curl --silent "https://api.github.com/repos/docker/compose/releases/latest" | grep -Po '"tag_name":\ "\K.*?(?=")'
  register: docker_compose_version
  changed_when: false
  args:
    executable: /usr/bin/bash

- name: install docker-compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version.stdout }}/docker-compose-Linux-x86_64
    dest: /usr/local/sbin/docker-compose
    mode: "0755"

- name: install docker python package
  become: true
  pip:
    name: docker-compose
