{% if item.registry is defined %}
    FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
    FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
    {% for var, value in item.env.items() %}
        {% if value %}
            ENV {{ var }} {{ value }}
        {% endif %}
    {% endfor %}
{% endif %}

RUN mkdir -p ~/.ssh && echo "should be below" > ~/.ssh/config && touch ~/.ssh/identity_file
