---
- name: Run when at least one disk found
  when:
    - crypttab__add_entry__disk_data_list | length > 0
  become: true
  block:
    - name: Register uuid for disks
      ansible.builtin.command: lsblk -lnd -o UUID {{ item.disk_path }}
      register: crypttab__add_entry__disk_path_uuid_results
      loop: "{{ crypttab__add_entry__disk_data_list }}"
      changed_when: true

    - name: Remove (old) crypttab entry for {{ fstab__add_entry__data_list }}
      ansible.builtin.lineinfile:
        path: "/etc/fstab"
        regexp: "^{{ item.partition_name }}"
        state: absent
      loop: "{{ fstab__add_entry__data_list }}"

    - name: Add crypttab entry for '{{ crypttab__add_entry__disk_data_list | map(attribute='partition_name') }}''
      ansible.builtin.lineinfile:
        path: /etc/crypttab
        line: "{{ crypttab_line }}"
        regexp: "{{ crypttab_line }}"
      loop: "{{ crypttab__add_entry__disk_data_list }}"
      loop_control:
        index_var: index
      vars:
        disk_uuid:
          "{{ crypttab__add_entry__disk_path_uuid_results.results[index].stdout }}"
        options: "{{ item.options | join(',') }}"
        crypttab_line: >-
          {{ item.partition_name }} UUID={{ disk_uuid }}
          {{ luks__open__keyfile_path }} {{ options }}