---
- name: Make sure dir exists - {{ immich__docker_setup__dir_path }}
  ansible.builtin.file:
    path: "{{ immich__docker_setup__dir_path }}"
    state: directory

- name: Copy templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ immich__docker_setup__dir_path }}/{{ file_name }}"
  with_fileglob:
    - "templates/*.j2"
    - "templates/.*.j2"
  vars:
    file_name: "{{ item | basename | regex_replace('\\.j2$', '') }}"

- name: Start immich compose

  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ immich__docker_setup__dir_path }}"
    state: present