---
# - name: Get disk with boot partition
#   ansible.builtin.shell: lsblk -sdln -o NAME,MOUNTPOINT | awk '$2 == "/boot"' | awk '{ print $1 }' | sed 's/.$//'
#   register: get_boot_disk_result
#   changed_when: get_boot_disk_result.stdout_lines | length != 1

# - name: Get disk(s) with mounted partition(s)
#   ansible.builtin.shell: lsblk -sdlfn -o NAME,MOUNTPOINT,TYPE | awk 'NF!=2' | awk '$3 != "lvm"' | awk '{ print $1 }' | sed 's/[0-9]//g' | uniq
#   register: get_disk_mounted_result
#   changed_when: get_boot_disk_result.stdout_lines | length > 0

#- name: Get disk(s) without 
#  ansible.builtin.shell: lsblk -sdlfn -o NAME,MOUNTPOINT,TYPE | awk '$3 != "lvm"' | awk '{ print $1 }' | sed 's/[0-9]//g' | uniq --unique
#  register: get_hard_drives__result
#  changed_when: get_hard_drives__result.stdout_lines | length > 0
#  when: get_hard_drives__unmounted

- name: Get disk(s) without filesystem
  ansible.builtin.shell: >-
    lsblk -sdlfn -o NAME,FSTYPE | awk '$2 == ""'
    | awk '{ print $1 }' | sed 's/[0-9]//g' | uniq --unique
  register: hdd__get_all__no_filesystem_result
  changed_when:
    hdd__get_all__no_filesystem_result.stdout_lines | length > 0
  when: hdd__get_all__no_filesystem

- name: Get partition(s) with filesystem
  ansible.builtin.shell: >-
    lsblk -sdlfn -o NAME,FSTYPE,TYPE | awk '$1!~/sda/'
    | awk '$1~/sd/'
    | awk '$2 == "{{ hdd__get_all__with_filesystem_type }}"'
    | awk '{ print $1 }'
  register: hdd__get_all__with_filesystem_result
  changed_when:
    hdd__get_all__with_filesystem_result.stdout_lines | length > 0
  when: hdd__get_all__with_filesystem

- name: Set fact 'hdd__get_all__no_filesystem_result'
  ansible.builtin.set_fact:
    hdd__get_all__no_filesystem_result:
      "{{ hdd__get_all__no_filesystem_result.stdout_lines }}"
  when: hdd__get_all__no_filesystem

- name: Set fact 'hdd__get_all__with_filesystem_result'
  ansible.builtin.set_fact:
    hdd__get_all__with_filesystem_result: 
      "{{ hdd__get_all__with_filesystem_result.stdout_lines }}"
  when: hdd__get_all__with_filesystem