---
- name: Get hdd(s) path(s)
  ansible.builtin.shell: >-
    lsblk -lnd -o PATH,TYPE,ROTA |
    awk '$2 == "disk"' |
    awk '$3 == "1"' |
    awk '{ print $1 }'
  register: hdd__get_all__paths_result
  changed_when: true

- name: Set fact 'hdd__get_all__paths_result'
  ansible.builtin.set_fact:
    hdd__get_all__paths_result:
      "{{ hdd__get_all__paths_result.stdout_lines }}"

- name: Get hdd(s) path(s) with number of partition(s)
  ansible.builtin.shell: >-
    lsblk -ln  {{ item }} |
    echo
    "{
      \"disk_path\": \"{{ item }}\",
      \"partitions_total\": $(tail -n +2 | wc -l)
    }"
  register: hdd__get_all__paths_and_partitions_result_temp
  loop: "{{ hdd__get_all__paths_result }}"
  changed_when: true

- name: Set fact 'hdd__get_all__paths_and_partitions_result'
  ansible.builtin.set_fact:
    hdd__get_all__paths_and_partitions_result:
      "{{ append }}"
  loop: "{{ hdd__get_all__paths_and_partitions_result_temp.results }}"
  vars:
    item_dict: "{{ item.stdout | from_json | from_yaml }}"
    append: >-
      {{
         hdd__get_all__paths_and_partitions_result |
         default([]) + [item_dict]
      }}

- name: Set fact 'hdd__get_all__no_partitions_disk_paths_result'
  ansible.builtin.set_fact:
    hdd__get_all__no_partitions_disk_paths_result: 
      "{{ append }}"
  loop: "{{ hdd__get_all__paths_and_partitions_result }}"
  vars:
    append: >-
      {{
         hdd__get_all__no_partitions_disk_paths_result |
         default([]) + [item.disk_path]
      }}
  when: item.partitions_total == 0

- name: Get ext4 hdd(s) partition(s) mount dir path
  ansible.builtin.shell: >-
    lsblk -ln -o name,fstype,type,rota |
    awk '$2 == "ext4" && $4 == "1"' |
    awk '{ print $1 }' |
    xargs -I "{}" grep "{}" /etc/fstab |
    awk '{ print $2 }'
  register: hdd__get_all__ext4_partition_mount_dir_paths_result
  changed_when: true