services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/pi/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    # networks:
    #    - bridge

volumes:
  caddy_data:
    external: true
  caddy_config:

# networks:
#    bridge:
#      name: bridge
#      external: true