setup_b2_buckets__bucket_name_uuid: ""
setup_b2_buckets__accounts:
  [
    {
      "master_key_id": "",
      "master_key": "",
      "profile_name": "",
      "bucket_name": "",
    },
  ]

setup_b2_buckets__bucket_key_suffix: "-key"

setup_b2_buckets__result:
  {
    "existsAlready": false,
    "buckets_data": [ { "bucket_name": "", "bucket_key": "" } ],
  }
