- name: Get field
  ansible.builtin.set_fact:
    "{{ item.bitwarden__get_field__fact_name }}": "{{ lookup('community.general.bitwarden', item.bitwarden__get_field__entry_name , field=item.bitwarden__get_field__field_name | default('password')) | regex_replace(\"^(\\[')(.*)('\\])$\", '\\2') }}"
  loop: "{{ get_bitwarden__field__fields }}"

#           {
#             "bitwarden__get_field__fact_name": "",
#             "bitwarden__get_field__entry_name": "",
#             "bitwarden__get_field__field_name": "",
#           },