FROM jrei/systemd-debian:latest as build

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
--mount=target=/var/cache/apt,type=cache,sharing=locked \
rm -f /etc/apt/apt.conf.d/docker-clean \
&& apt-get update \
&& apt-get install -y --no-install-recommends \
libguestfs-tools\
qemu qemu-kvm libvirt-clients libvirt-daemon-system virtinst bridge-utils \
&& rm -rf /var/lib/apt/lists/* \
&& rm -rf /usr/share/doc && rm -rf /usr/share/man \
&& apt-get clean

WORKDIR "/root"

ADD {{ debian_vm_image_file }} .

#RUN virt-copy-out -a {{ debian_vm_image_file }} /boot/vmlinuz-{{ debian_kernel_version }}-{{ debian_architecture }} /boot/initrd.img-{{ debian_kernel_version }}-{{ debian_architecture }} .

#FROM scratch AS export-boot-files
#COPY --from=build /root/* .

