---
- name: Run when at least one drive found
  when: luks__open__disk_path_list | length > 0
  become: true
  block:
    - name: Set fact 'luks__open__disks_with_partition_name'
      ansible.builtin.set_fact:
        luks__open__disks_with_partition_name: >-
          {{
            luks__open__disks_with_partition_name | default([]) +
            [{
                'disk_path': item,
                'partition_name': partition_name
            }]
          }}
      loop: "{{ luks__open__disk_path_list }}"
      vars:
        partition_name: "{{ item.split('/')[-1] }}0_crypt"

    - name: Open '{{ luks__open__disk_path_list }}'
      community.crypto.luks_device:
        device: "{{ item.disk_path }}"
        state: "opened"
        name: "{{ item.partition_name }}"
        keyfile: "{{ luks__open__keyfile_path }}"
      loop: "{{ luks__open__disks_with_partition_name }}"

    - name: Return disk paths with partition as 'luks__open__disk_data_list_result'
      ansible.builtin.set_fact:
        luks__open__disk_data_list_result: "{{ appended }}"
      loop: "{{ luks__open__disks_with_partition_name }}"
      vars:
        appended: >-
          {{
              luks__open__disk_data_list_result | default([]) +
              [
                {
                "disk_path": item.disk_path,
                "partition_path": "/dev/mapper/" + item.partition_name,
                "partition_name": item.partition_name
                }
              ]
          }}
