---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible