---
- name: install rust
  shell: set -o pipefail && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
  changed_when: false
  args:
    executable: /usr/bin/bash
