---
- name: Make sure dir exists - {{ restic__docker_setup__dir_path }}
  ansible.builtin.file:
    path: "{{ restic__docker_setup__dir_path }}"
    state: directory

- name: Copy templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ restic__docker_setup__dir_path }}/{{ file_name }}"
  with_fileglob: "templates/*.j2"
  vars:
    file_name: "{{ item | basename | regex_replace('\\.j2$', '') }}"

- name: Build and run once
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ restic__docker_setup__dir_path }}"
    build: always
    recreate: always
