---
- name: Wipe {{ hdd__wipe__disk_paths }}
  become: true
  when: 
    - hdd__wipe__disk_paths is defined
    - hdd__wipe__disk_paths | length > 0
  register: hdd__wipe__disk_paths_result
  ansible.builtin.command: dd if=/dev/zero of={{ item }} bs=4096
  loop: "{{ hdd__wipe__disk_paths }}"
  changed_when: hdd__wipe__disk_paths | length > 0
  failed_when: '"No space left on device" not in hdd__wipe__disk_paths_result.stderr'
