fstab__add_entry__data_list:
  - partition_path: null
    partition_name: null
    partition_filesystem: null
    mount_root_dir_name: null
    mount_root_dir_path: null
    mount_dir_owner: null
    systemd_idle_timeout_sec: null

fstab__add_entry__load_automount: []
