---
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages: ["docker", "docker-engine"]

- name: Install required system packages to install docker
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      [
        "apt-transport-https",
        "ca-certificates",
        "curl",
        "lsb-release",
        "gnupg2",
      ]

- name: Create keyrings dir
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker apt key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ docker__install__distribution }}/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0644"
    force: true

- name: Register architecture
  ansible.builtin.command: dpkg --print-architecture
  register: docker__install__architecture_result
  changed_when: true

- name: Add apt repo
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ docker__install__architecture_result.stdout }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/{{ docker__install__distribution }}
      {{ docker__install__distribution_release }} stable
    state: present
    mode: "0755"

- name: Install docker (compose)
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      [
        "docker-ce",
        "docker-ce-cli",
        "containerd.io",
        "docker-buildx-plugin",
        "docker-compose-plugin",
      ]

# - name: Ensure group "docker" exists
#   ansible.builtin.group:
#     name: docker
#     state: present

# - name: Add the current user to docker group
#   ansible.builtin.user:
#     name: "{{ lookup('env', 'USER') }}"
#     group: docker

# - name: Restart docker service
#   ansible.builtin.service:
#     name: docker
#     state: restarted

- name: Ensure Docker is started and enabled at boot.
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
