- name: Create mirror for '{{ zfs__create_pool__disk_path_list }}'
  become: true
  ansible.builtin.command: >-
    zpool create {{ zfs__create_pool__pool_name }} \
    -o ashift=12 \
    -O normalization=formD \
    -O compression=lz4 \
    -O atime=off \
    -O mountpoint={{ zfs__create_pool__mount_path }} \
    mirror {{ disk_paths }}
  when:
    - zfs__create_pool__type == "mirror"
    - zfs__create_pool__disk_path_list is iterable
    - (zfs__create_pool__disk_path_list | length) > 1
  vars:
    disk_paths: "{{ zfs__create_pool__disk_path_list | join(' ') }}"
