---
- name: Make sure dirs exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ caddy__add_site__sub_configs_dir_path }}"

- name: Copy caddy site template
  ansible.builtin.template:
    src: "site.Caddyfile.j2"
    dest: >-
      {{ caddy__add_site__sub_configs_dir_path }}/
      {{- item.file_name }}
  loop: "{{ caddy__add_site__site_list }}"

- name: Reload caddy
  become: true
  community.docker.docker_container_exec:
    container: "{{ caddy__add_site__container_name }}"
    command: "caddy reload"
    chdir: "/etc/caddy"