---
- name: Make sure dirs exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ tailscale__docker_setup__dir_path }}"

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Copy templates
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ tailscale__docker_setup__dir_path }}/compose.yml"

- name: Start tailscale container
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ tailscale__docker_setup__dir_path }}"
    state: present
