---
- name: Convert
  block:
    - name: Convert
      ansible.builtin.set_fact:
        backup__create_dirs__convert_from_fstab_output: >-
          {{
            backup__create_dirs__convert_from_fstab_output |
            default([]) + append
          }}
      loop: "{{ backup__create_dirs__convert_from_fstab_input }}"
      vars:
        root_dir_path: >-
          {{ item.mount_root_dir_path }}/{{ item.partition_name }}
        backup_dir_name: "backup"
        backup_dir_path: "{{ root_dir_path }}/{{ backup_dir_name }}"
        append:
          - root_dir_path: "{{ root_dir_path }}"
            backup_dir_name: "{{ backup_dir_name }}"
            backup_dir_path: "{{ backup_dir_path }}"
            backup_dir_owner: "{{ item.backup_dir_owner }}"

    - name: Append
      ansible.builtin.set_fact:
        backup__create_dirs__input: >-
          {{
            backup__create_dirs__input |
            default([]) +
            backup__create_dirs__convert_from_fstab_output
          }}
  when: 
    - backup__create_dirs__convert_from_fstab_input is defined
    - backup__create_dirs__convert_from_fstab_input | length > 0
