FROM caddy:2.8.4-builder@sha256:efb0a066246f690811b6063d74e5ba633f62286ed15f39f6eb3d05c2a870a2fe AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/hetzner

FROM caddy:{{ caddy__docker_setup__version }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy