FROM docker.io/caddy:2.8.1-builder@sha256:37acf9e88ea74ef051bc1ec68ea9abd535320ea4eea1a0162aaf378ee5200a3c AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/hetzner

FROM caddy:{{ caddy__docker_setup__version }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy