---
- name: Generate password
  ansible.builtin.command: bw generate -uln --length {{ bitwarden__generate_password__length }}
  register: bitwarden__generate_password__result
  ignore_errors: true
  changed_when: true

- name: Set 'bitwarden__generate_password__result'
  ansible.builtin.set_fact:
    bitwarden__generate_password__result: "{{ bitwarden__generate_password__result.stdout }}"
