---
# ansible-playbook -i staging.yml --ask-become-pass playbooks/test_vm__setup.yml
- name: Setup test vm
  hosts: localhost
  environment:
    # PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  vars:
    # ansible_python_interpreter: "/home/roman/projects/personal/ansible-roles/.venv/bin/python"

  roles:
    - role: bitwarden/bitwarden__create_folder
      delegate_to: localhost
    - role: bitwarden/bitwarden__generate_password
      delegate_to: localhost
    - role: bitwarden/bitwarden__create_item
      delegate_to: localhost
    - role: ssh/ssh__create_keypair
      delegate_to: localhost
    - role: ssh/ssh__create_config
      delegate_to: localhost
    - role: docker__install
      delegate_to: localhost
    - role: iso__create_debian_preseed
      delegate_to: localhost
    - role: vm/vm__setup_debian
      delegate_to: localhost

