vm__setup_debian__pip_virtualenv:
  "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV', default='.venv') }}"

vm__setup_debian__scripts_dir_path: null
vm__setup_debian__files_dir_path: null
vm__setup_debian__iso_dir_path: null
vm__setup_debian__image_file: null

vm__setup_debian__hdd_image_name: null
vm__setup_debian__hdd_image_format: null
vm__setup_debian__hdd_image_quantity: null

vm__setup_debian__qemu_monitor_socket_path: null
vm__setup_debian__vm_net: null
vm__setup_debian__vm_dhcp_start_address: null
vm__setup_debian__vm_tmp_image_file_path: null
vm__setup_debian__vm_image_format: null
vm__setup_debian__vm_tmp_iso_file_path: null
vm__setup_debian__vm_ip: null
vm__setup_debian__vm_tmp_dir_path: null
vm__setup_debian__vm_persistent_dir_path: null
vm__setup_debian__vm_kernel_img_name: null
vm__setup_debian__vm_initrd_img_name: null


vm__setup_debian__image_size: 5G
vm__setup_debian__hdd_image_size: 1G
vm__setup_debian__ssh_port: "22"
vm__setup_debian__ssh_host: localhost

vm__setup_debian__extract_img_name: "1.img"
vm__setup_debian__extract_img_file_path: 
  "{{ vm__setup_debian__vm_tmp_dir_path }}/{{ vm__setup_debian__extract_img_name }}"
#vm__setup_debian__extract_kernel_img_file: "boot/{{ vm__setup_debian__vm_kernel_img_name }}"
#vm__setup_debian__extract_initrd_img_file: "boot/{{ vm__setup_debian__vm_initrd_img_name }}"

vm__setup_debian__become: true
vm__setup_debian__is_encrypted: false
vm__setup_debian__crypt_password: ""
vm__setup_debian__ssh_dropbear_root_password: ""

vm__setup_debian__extract_kernel_img_file: >-
  {%- if vm__setup_debian__is_encrypted -%}
  {{- vm__setup_debian__vm_kernel_img_name -}}
  {%- else -%}
  boot/{{ vm__setup_debian__vm_kernel_img_name -}}
  {%- endif %}
vm__setup_debian__extract_initrd_img_file: >-
  {%- if vm__setup_debian__is_encrypted -%}
  {{- vm__setup_debian__vm_initrd_img_name -}}
  {%- else -%}
  boot/{{ vm__setup_debian__vm_initrd_img_name -}}
  {%- endif %}
