---
- name: Converge
  hosts: all
  tasks:
    - name: "Include create_user"
      include_role:
        name: "create_user"
      vars:
        - create_user_name: "test"
        - create_user_password: "123456"
        - create_user_password_salt: "123456"
        - create_user_shell: "/bin/bash"
