---
- name: Build backup paths from {{ create_backup_dirs__disks_mount_dir_paths }}
  ansible.builtin.set_fact:
    create_backup_dirs__disks_backup_dir_paths: |
      {{ create_backup_dirs__disks_backup_dir_paths
       + [ item + "/" + create_backup_dirs__dir_name ] }} 
  loop: "{{ create_backup_dirs__disks_mount_dir_paths }}"

- name: Create backup dir for {{ create_backup_dirs__disks_backup_dir_paths }}
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ create_backup_dirs__backup_dir_owner }}"
    group: "{{ create_backup_dirs__backup_dir_owner }}"
    mode: '0755'
  loop: "{{ create_backup_dirs__disks_backup_dir_paths }}"

- name: Try find main backup dir
  ansible.builtin.find:
    paths: "{{ item }}"
    file_type: file
    patterns: "{{ create_backup_dirs__main_dir_marker_file }}"
    hidden: true
  loop: "{{ create_backup_dirs__disks_backup_dir_paths }}"
  register: create_backup_dirs__main_dir_marker_file_results

- name: Extract files from '{{ create_backup_dirs__main_dir_marker_file_results }}'
  ansible.builtin.set_fact:
    create_backup_dirs__main_backup_dir_found_files: |
      {{ create_backup_dirs__main_backup_dir_found_files + [ files ] | flatten  }}
  loop: "{{ create_backup_dirs__main_dir_marker_file_results.results }}"
  when: files | length > 0
  vars:
    files: "{{ item.files }}"

- name: Try find main backup path
  when: create_backup_dirs__main_backup_dir_found_files | length == 1
  ansible.builtin.set_fact:
    create_backup_dirs__main_backup_dir_path: >-
      {{ create_backup_dirs__main_backup_dir_found_files[0].path |
      replace('.' + create_backup_dirs__main_dir_marker_file_name, '')}}

- name: Mark main backup dir
  when: create_backup_dirs__main_backup_dir_found_files | length == 0
  block:
    - name: Mark main backup dir when no found - {{ create_backup_dirs__main_backup_dir_path }}
      ansible.builtin.file:
        path: "{{ create_backup_dirs__main_backup_dir_path }}"
        state: touch
        owner: "{{ create_backup_dirs__backup_dir_owner }}"
        group: "{{ create_backup_dirs__backup_dir_owner }}"
        mode: '0644'

    - name: Set fact for 'create_backup_dirs__main_backup_dir_path'
      ansible.builtin.set_fact:
        create_backup_dirs__main_backup_dir_path: "{{ create_backup_dirs__main_backup_dir_path }}"

- name: Set fact create_backup_dirs__disks_backup_dir_paths
  ansible.builtin.set_fact:
    create_backup_dirs__result: "{{ create_backup_dirs__disks_backup_dir_paths }}"